# https://github.com/kdheepak/panvimdoc
name: panvimdoc

on: [push]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: pandoc to vimdoc
    steps:
      - uses: actions/checkout@v2
      - uses: kdheepak/panvimdoc@main
        with:
          vimdoc: code_runner
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(docs): Auto generate docs"
          version: "NVIM v0.10.0"
          branch: ${{ github.head_ref }}
